
package pe.mcg.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Feb 21 11:12:27 COT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "listarUsuariosResponse", namespace = "service.ws.mcg.pe")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarUsuariosResponse", namespace = "service.ws.mcg.pe")

public class ListarUsuariosResponse {

    @XmlElement(name = "return")
    private java.util.List<pe.mcg.ws.beans.UsuarioEntity> _return;

    public java.util.List<pe.mcg.ws.beans.UsuarioEntity> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<pe.mcg.ws.beans.UsuarioEntity> new_return)  {
        this._return = new_return;
    }

}

