
package pe.mcg.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Feb 21 11:12:27 COT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "obtenerUsuario", namespace = "service.ws.mcg.pe")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerUsuario", namespace = "service.ws.mcg.pe")

public class ObtenerUsuario {

    @XmlElement(name = "arg0")
    private java.lang.Integer arg0;

    public java.lang.Integer getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Integer newArg0)  {
        this.arg0 = newArg0;
    }

}

