package pe.mcg.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-21T11:13:30.986-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "UsuarioServiceImplService", 
                  wsdlLocation = "file:/D:/MCG/CLASE_05/FinalProject/WSProject/WebContent/wsdl/usuarioserviceimpl.wsdl",
                  targetNamespace = "service.ws.mcg.pe") 
public class UsuarioServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("service.ws.mcg.pe", "UsuarioServiceImplService");
    public final static QName UsuarioServiceImplPort = new QName("service.ws.mcg.pe", "UsuarioServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/MCG/CLASE_05/FinalProject/WSProject/WebContent/wsdl/usuarioserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UsuarioServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/MCG/CLASE_05/FinalProject/WSProject/WebContent/wsdl/usuarioserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UsuarioServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsuarioServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UsuarioService
     */
    @WebEndpoint(name = "UsuarioServiceImplPort")
    public UsuarioService getUsuarioServiceImplPort() {
        return super.getPort(UsuarioServiceImplPort, UsuarioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioService
     */
    @WebEndpoint(name = "UsuarioServiceImplPort")
    public UsuarioService getUsuarioServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UsuarioServiceImplPort, UsuarioService.class, features);
    }

}
