package pe.mcg.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-21T11:13:30.971-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "service.ws.mcg.pe", name = "UsuarioService")
@XmlSeeAlso({ObjectFactory.class})
public interface UsuarioService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarUsuario", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.InsertarUsuario")
    @WebMethod(action = "urn:InsertarUsuario")
    @ResponseWrapper(localName = "insertarUsuarioResponse", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.InsertarUsuarioResponse")
    public boolean insertarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        pe.mcg.ws.service.UsuarioEntity arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ListarUsuarios")
    @WebMethod(action = "urn:ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ListarUsuariosResponse")
    public java.util.List<pe.mcg.ws.service.UsuarioEntity> listarUsuarios();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ActualizarUsuario")
    @WebMethod(action = "urn:ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ActualizarUsuarioResponse")
    public boolean actualizarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        pe.mcg.ws.service.UsuarioEntity arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "desactivarUsuario", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.DesactivarUsuario")
    @WebMethod(action = "urn:DesactivarUsuario")
    @ResponseWrapper(localName = "desactivarUsuarioResponse", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.DesactivarUsuarioResponse")
    public boolean desactivarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        pe.mcg.ws.service.UsuarioEntity arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuario", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ObtenerUsuario")
    @WebMethod(action = "urn:ObtenerUsuario")
    @ResponseWrapper(localName = "obtenerUsuarioResponse", targetNamespace = "service.ws.mcg.pe", className = "pe.mcg.ws.service.ObtenerUsuarioResponse")
    public pe.mcg.ws.service.UsuarioEntity obtenerUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
