
package pe.mcg.ws.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-21T11:13:30.828-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class UsuarioService_UsuarioServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("service.ws.mcg.pe", "UsuarioServiceImplService");

    private UsuarioService_UsuarioServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UsuarioServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UsuarioServiceImplService ss = new UsuarioServiceImplService(wsdlURL, SERVICE_NAME);
        UsuarioService port = ss.getUsuarioServiceImplPort();  
        
        {
        System.out.println("Invoking insertarUsuario...");
        pe.mcg.ws.service.UsuarioEntity _insertarUsuario_arg0 = new pe.mcg.ws.service.UsuarioEntity();
        _insertarUsuario_arg0.setClave("Clave1135164778");
        _insertarUsuario_arg0.setCorreo("Correo-1916528484");
        _insertarUsuario_arg0.setId(Integer.valueOf(-493349906));
        _insertarUsuario_arg0.setNombreCompleto("NombreCompleto-935601850");
        _insertarUsuario_arg0.setUsuario("Usuario-1707605325");
        boolean _insertarUsuario__return = port.insertarUsuario(_insertarUsuario_arg0);
        System.out.println("insertarUsuario.result=" + _insertarUsuario__return);


        }
        {
        System.out.println("Invoking listarUsuarios...");
        java.util.List<pe.mcg.ws.service.UsuarioEntity> _listarUsuarios__return = port.listarUsuarios();
        System.out.println("listarUsuarios.result=" + _listarUsuarios__return);


        }
        {
        System.out.println("Invoking actualizarUsuario...");
        pe.mcg.ws.service.UsuarioEntity _actualizarUsuario_arg0 = new pe.mcg.ws.service.UsuarioEntity();
        _actualizarUsuario_arg0.setClave("Clave1971794574");
        _actualizarUsuario_arg0.setCorreo("Correo850870013");
        _actualizarUsuario_arg0.setId(Integer.valueOf(-297372604));
        _actualizarUsuario_arg0.setNombreCompleto("NombreCompleto1568226403");
        _actualizarUsuario_arg0.setUsuario("Usuario296788885");
        boolean _actualizarUsuario__return = port.actualizarUsuario(_actualizarUsuario_arg0);
        System.out.println("actualizarUsuario.result=" + _actualizarUsuario__return);


        }
        {
        System.out.println("Invoking desactivarUsuario...");
        pe.mcg.ws.service.UsuarioEntity _desactivarUsuario_arg0 = new pe.mcg.ws.service.UsuarioEntity();
        _desactivarUsuario_arg0.setClave("Clave2037958429");
        _desactivarUsuario_arg0.setCorreo("Correo999707173");
        _desactivarUsuario_arg0.setId(Integer.valueOf(-1800950672));
        _desactivarUsuario_arg0.setNombreCompleto("NombreCompleto-1679895908");
        _desactivarUsuario_arg0.setUsuario("Usuario2084260854");
        boolean _desactivarUsuario__return = port.desactivarUsuario(_desactivarUsuario_arg0);
        System.out.println("desactivarUsuario.result=" + _desactivarUsuario__return);


        }
        {
        System.out.println("Invoking obtenerUsuario...");
        java.lang.Integer _obtenerUsuario_arg0 = Integer.valueOf(-1598270412);
        pe.mcg.ws.service.UsuarioEntity _obtenerUsuario__return = port.obtenerUsuario(_obtenerUsuario_arg0);
        System.out.println("obtenerUsuario.result=" + _obtenerUsuario__return);


        }

        System.exit(0);
    }

}
