
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package pe.mcg.ws.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-21T11:13:30.942-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "UsuarioServiceImplService",
                      portName = "UsuarioServiceImplPort",
                      targetNamespace = "service.ws.mcg.pe",
                      wsdlLocation = "file:/D:/MCG/CLASE_05/FinalProject/WSProject/WebContent/wsdl/usuarioserviceimpl.wsdl",
                      endpointInterface = "pe.mcg.ws.service.UsuarioService")
                      
public class UsuarioServiceImpl implements UsuarioService {

    private static final Logger LOG = Logger.getLogger(UsuarioServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see pe.mcg.ws.service.UsuarioService#insertarUsuario(pe.mcg.ws.service.UsuarioEntity  arg0 )*
     */
    public boolean insertarUsuario(pe.mcg.ws.service.UsuarioEntity arg0) { 
        LOG.info("Executing operation insertarUsuario");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.mcg.ws.service.UsuarioService#listarUsuarios(*
     */
    public java.util.List<pe.mcg.ws.service.UsuarioEntity> listarUsuarios() { 
        LOG.info("Executing operation listarUsuarios");
        try {
            java.util.List<pe.mcg.ws.service.UsuarioEntity> _return = new java.util.ArrayList<pe.mcg.ws.service.UsuarioEntity>();
            pe.mcg.ws.service.UsuarioEntity _returnVal1 = new pe.mcg.ws.service.UsuarioEntity();
            _returnVal1.setClave("Clave-1245012475");
            _returnVal1.setCorreo("Correo-429494667");
            _returnVal1.setId(Integer.valueOf(1871119398));
            _returnVal1.setNombreCompleto("NombreCompleto-1320654093");
            _returnVal1.setUsuario("Usuario1954747356");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.mcg.ws.service.UsuarioService#actualizarUsuario(pe.mcg.ws.service.UsuarioEntity  arg0 )*
     */
    public boolean actualizarUsuario(pe.mcg.ws.service.UsuarioEntity arg0) { 
        LOG.info("Executing operation actualizarUsuario");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.mcg.ws.service.UsuarioService#desactivarUsuario(pe.mcg.ws.service.UsuarioEntity  arg0 )*
     */
    public boolean desactivarUsuario(pe.mcg.ws.service.UsuarioEntity arg0) { 
        LOG.info("Executing operation desactivarUsuario");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see pe.mcg.ws.service.UsuarioService#obtenerUsuario(java.lang.Integer  arg0 )*
     */
    public pe.mcg.ws.service.UsuarioEntity obtenerUsuario(java.lang.Integer arg0) { 
        LOG.info("Executing operation obtenerUsuario");
        System.out.println(arg0);
        try {
            pe.mcg.ws.service.UsuarioEntity _return = new pe.mcg.ws.service.UsuarioEntity();
            _return.setClave("Clave-268857696");
            _return.setCorreo("Correo498071887");
            _return.setId(Integer.valueOf(-1509639796));
            _return.setNombreCompleto("NombreCompleto-243277874");
            _return.setUsuario("Usuario1134900449");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
